### ISSUE TITLE
调gridcontroller的remove方法，全部remove后调用gridcontroller的append方法会抛异常

### ISSUE THREAD

**Issue by hxmeie** [flutter-library-provider/DragGrid#2]
The following assertion was thrown building DragTarget<int>(state: _DragTargetState<int>#f7a7a):
BoxConstraints has a negative minimum height.

The offending constraints were: BoxConstraints(w=66.0, h=-8.4; NOT NORMALIZED)

**Comment by linpengteng** [comment]
Thank you, now is fixed~
