### ISSUE TITLE
Using mainAxisExtent instead of childAspectRatio results in wrong drag item size

### ISSUE THREAD

**Issue by ultimate-tester** [flutter-library-provider/DragGrid#3]
The SliverGridDelegateWithFixedCrossAxisCount delegate supports the use of either a childAspectRatio or a mainAxisExtent. This library assumes that childAspectRatio will always be used and when using mainAxisExtent, the wrong size will be calculated for the drag item (it defaults to 1.0 aspect ratio resulting in a square widget, but the original widget may not have been square at all).

Demonstration:
![demo](https://github.com/user-attachments/assets/9bc69a20-26da-459b-9c03-6716240a192c)

The issue lays in drag_grid_helper.dart, line 298 where childAspectRatio is used for calculating the height. Here a distinguishment should be made between childAspectRatio and mainAxisExtent. If mainAxisExtent is set on the delegate, then it should be used in the calculation.

If appreciated, I can submit a PR.

**Comment by linpengteng** [comment]
You are right, very thanks!

**Comment by linpengteng** [comment]
I happen to have some time today, I'll try to fix it. If you find any other problems, you can directly submit a PR.
